language: cpp
dist: trusty

env:
    - PREMAKEURL=https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-linux.tar.gz

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y p7zip-full
    - wget -O ./tools/premake5.tgz $PREMAKEURL
    - tar -xz -f ./tools/premake5.tgz -C ./tools

install:
    - tools/premake5 gmake
    - make -C _build

script:
    - chdir _output/test
    - ./test_list_contents
