language: cpp
dist: trusty

env:
    global:
        - PREMAKEURL=https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-linux.tar.gz
    matrix:
        - CONFIG=release_x86_64 ARCHSPEC=amd64
        #- CONFIG=release_x86    ARCHSPEC=i386

install:
    - sudo apt-get update
    - sudo apt-get install -y p7zip-full:$ARCHSPEC gcc-multilib g++-multilib
    - wget -O ./tools/premake5.tgz $PREMAKEURL
    - tar -xz -f ./tools/premake5.tgz -C ./tools
    - tools/premake5 gmake
    - make -C _build config=$CONFIG

script:
    - cd _output/test
    - ./test_list_contents
