
version: 0.1.{build}

environment:
    matrix:
        - VSVER: vs2010
          VSTOOLS: '%VS100COMNTOOLS%\\..\\..\\VC'
        - VSVER: vs2013
          VSTOOLS: '%VS120COMNTOOLS%\\..\\..\\VC'
        - VSVER: vs2015
          VSTOOLS: '%VS140COMNTOOLS%\\..\\..\\VC'

install:
- cmd: call "%VSTOOLS%\vcvarsall.bat" x64

build_script:
- cmd: tools\premake5 %VSVER%
- cmd: msbuild /p:Configuration=Release _build\Lib7z.sln

test_script:
- cmd: chdir "%APPVEYOR_BUILD_FOLDER%\_output\test"
- cmd: test_list_contents.exe
- cmd: chdir "%APPVEYOR_BUILD_FOLDER%"
